In [1]:
import numpy as np

In [2]:
arr1=np.arange(10)
arr2=np.arange(10,20)

In [3]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
arr1*2  #모든 원소의 값을 2배 해준다

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr1 +10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
arr1  #단 배열 자체가 변하진 않는다

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr1=arr1*2
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arr1=np.arange(10)

In [15]:
arr3=arr1+arr2

In [16]:
arr3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])