In [3]:
import numpy as np  # allias

arr1=np.full(6,0)
arr2=np.zeros(6)
arr3=np.full(6,6)
arr4=np.ones(9)
arr5=np.random.random(6)
arr6=np.random.random(10)

In [4]:
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0.]
[6 6 6 6 6 6]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.44396137 0.41895755 0.35804359 0.95145206 0.60505528 0.66223923]
[0.33914976 0.06798771 0.83991632 0.18598607 0.64582649 0.99256706
 0.68773772 0.39167306 0.28821437 0.54534693]
