In [1]:
import numpy as np

In [2]:
arr1=np.array([2,3,5,7,11,13,17,19,23,29,31])

In [3]:
arr1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
arr1[1]

3

In [6]:
arr1[1:5]

array([ 3,  5,  7, 11])

In [7]:
arr1[-1]

31

In [9]:
arr1[-2]

29

In [10]:
arr1[[1,3,4]]   #arr1에서 1,3,4 번 위치에 있는 부분만 뽑아낸다

array([ 3,  7, 11])

In [11]:
arr2=np.array([2,1,3])

In [12]:
arr1[arr2]

array([5, 3, 7])

In [13]:
arr1[2:7]  #slicing

array([ 5,  7, 11, 13, 17])

In [14]:
arr1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [15]:
arr3=arr1[2:11:2]  # 슬라이싱을 하는데 2씩 건너뛰고 싶을 때

In [16]:
arr3

array([ 5, 11, 17, 23, 31])