In [1]:
import numpy as np

In [2]:
arr1=np.array([2,3,5,7,11,13,17,19,23,29,31])

In [4]:
arr1>4    # 원소 각각과 비교

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [5]:
arr1%2==0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [6]:
booleans=np.array([True,True,False,True,True,False,True,True,True,False,True])

In [7]:
np.where(booleans)  #True가 있는 값만 받아온다.

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

In [8]:
arr1>4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [9]:
np.where(arr1>4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [10]:
filter = np.where(arr1>4)    #인덱스만 추출된다
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [11]:
arr1[filter]     #추출된 인덱스의 값을 출력한다.

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])