In [1]:
import numpy  #numpy모듈을 불러옴

In [2]:
array1=numpy.array([2,3,5,7,11,13,17,19,23,29,31]) #numpy모듈의 array함수를 사용함. 이때 파이썬 리스트를 매개변수로 넘겨줌

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape  #array1에 몇개의 요소가 있는지

(11,)

In [6]:
array2=numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [7]:
type(array2)

numpy.ndarray

#### numpy.ndarray인 이유
ndarray => n차원 배열

In [8]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
array2.shape

(3, 4)

array.shape을 했을 때 (3,4)로 나오면, 3행 4열인 2차원 array라는 의미이다.

In [10]:
array1.size

11

In [11]:
array2.size

12

array1의 원소의 개수는 12개였고, array2는 3행 4열이어서 3 * 4 이므로 12이다.

In [12]:
print(array1)

[ 2  3  5  7 11 13 17 19 23 29 31]


In [13]:
arr3= numpy.full(6,7)  # 원소 개수는 6개, 그 값은 7로

In [14]:
arr3

array([7, 7, 7, 7, 7, 7])

In [15]:
arr4=numpy.full(6,0)
arr5=numpy.zeros(6,dtype=int)
print(arr4)
print(arr5)

[0 0 0 0 0 0]
[0 0 0 0 0 0]


In [17]:
arr6=numpy.full(6,1)
arr7=numpy.ones(6,dtype=int)
print(arr6)
print(arr7)

[1 1 1 1 1 1]
[1 1 1 1 1 1]


In [19]:
arr8=numpy.random.random(6)
arr9=numpy.random.random(6)
print(arr8)
print(arr9)

[0.99395317 0.81253022 0.04548678 0.41824444 0.64945338 0.31352201]
[0.27937825 0.3717489  0.22979138 0.27779359 0.79048524 0.74876131]


In [20]:
array10 = numpy.arange(6)
print(array10)

[0 1 2 3 4 5]


In [21]:
array11 = numpy.arange(2, 7)
print(array11)

[2 3 4 5 6]


In [22]:
array12 = numpy.arange(3, 17, 3)
print(array12)

[ 3  6  9 12 15]
